services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.encryptedSavedObjects.encryptionKey=${ES_ENCRYPTION_KEY}
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - xpack.security.encryptionKey=${KIBANA_ENCRYPTION_KEY}
      - xpack.encryptedSavedObjects.encryptionKey=${KIBANA_SO_ENCRYPTION_KEY}
      - xpack.reporting.encryptionKey=${KIBANA_REPORTING_KEY}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    restart: unless-stopped

volumes:
  es-data:

networks:
  elastic:
